insert data 
{ graph <http:cloudya.net/spinner/words> {
s:flasche rdfs:label 'flasche'@de
. s:flasche s:synonym s:champagner
. s:champagner rdfs:label 'Champagner'@de
. s:champagner s:id '/en/champagne'
. s:champagner s:score '27.881685'
. s:champagner s:mid '/m/0f2b9'
. s:champagner s:source 'freebase'
. s:champagner s:inGroup s:produktlinie
. s:produktlinie rdfs:label 'Produktlinie'@en
. s:produktlinie s:source 'freebase'
. s:produktlinie s:id '/business/product_line'
. s:flasche s:hasGroup s:produktlinie
. s:flasche s:synonym s:gasflasche
. s:gasflasche rdfs:label 'Gasflasche'@de
. s:gasflasche s:id '/en/gas_cylinder'
. s:gasflasche s:score '25.752462'
. s:gasflasche s:mid '/m/04dx1s'
. s:gasflasche s:source 'freebase'
. s:flasche s:synonym s:weinflasche
. s:weinflasche rdfs:label 'Weinflasche'@de
. s:weinflasche s:id '/en/wine_bottle'
. s:weinflasche s:score '25.544407'
. s:weinflasche s:mid '/m/020p1v'
. s:weinflasche s:source 'freebase'
. s:flasche s:synonym s:pet-flasche
. s:pet-flasche rdfs:label 'PET-Flasche'@de
. s:pet-flasche s:id '/en/plastic_bottles'
. s:pet-flasche s:score '24.754314'
. s:pet-flasche s:mid '/m/02rlncx'
. s:pet-flasche s:source 'freebase'
. s:pet-flasche s:inGroup s:schiffsrumpfmaterial
. s:schiffsrumpfmaterial rdfs:label 'Schiffsrumpfmaterial'@en
. s:schiffsrumpfmaterial s:source 'freebase'
. s:schiffsrumpfmaterial s:id '/boats/hull_material'
. s:flasche s:hasGroup s:schiffsrumpfmaterial
. s:flasche s:synonym s:bierflasche
. s:bierflasche rdfs:label 'Bierflasche'@de
. s:bierflasche s:id '/en/beer_bottle'
. s:bierflasche s:score '23.867506'
. s:bierflasche s:mid '/m/044gvx'
. s:bierflasche s:source 'freebase'
. s:flasche s:synonym s:babyflasche
. s:babyflasche rdfs:label 'Babyflasche'@de
. s:babyflasche s:id '/en/baby_bottle'
. s:babyflasche s:score '23.765417'
. s:babyflasche s:mid '/m/01fqc_'
. s:babyflasche s:source 'freebase'
. s:flasche s:synonym s:feldflasche
. s:feldflasche rdfs:label 'Feldflasche'@de
. s:feldflasche s:score '22.580681'
. s:feldflasche s:mid '/m/04lfm2_'
. s:feldflasche s:source 'freebase'
. s:flasche s:synonym s:graffiti
. s:graffiti rdfs:label 'Graffiti'@de
. s:graffiti s:id '/en/graffiti'
. s:graffiti s:score '22.397181'
. s:graffiti s:mid '/m/034wh'
. s:graffiti s:source 'freebase'
. s:graffiti s:inGroup s:kunstepoche_-bewegung
. s:kunstepoche_-bewegung rdfs:label 'Kunstepoche/-bewegung'@en
. s:kunstepoche_-bewegung s:source 'freebase'
. s:kunstepoche_-bewegung s:id '/visual_art/art_period_movement'
. s:flasche s:hasGroup s:kunstepoche_-bewegung
. s:flasche s:synonym s:druckluftflasche
. s:druckluftflasche rdfs:label 'Druckluftflasche'@de
. s:druckluftflasche s:id '/en/diving_cylinder'
. s:druckluftflasche s:score '21.271856'
. s:druckluftflasche s:mid '/m/02c70v'
. s:druckluftflasche s:source 'freebase'
. s:flasche s:synonym s:spritzflasche
. s:spritzflasche rdfs:label 'Spritzflasche'@de
. s:spritzflasche s:id '/en/wash_bottle'
. s:spritzflasche s:score '19.358618'
. s:spritzflasche s:mid '/m/03gqtlp'
. s:spritzflasche s:source 'freebase'
. s:flasche s:synonym s:tequila
. s:tequila rdfs:label 'Tequila'@de
. s:tequila s:id '/en/tequila'
. s:tequila s:score '18.700064'
. s:tequila s:mid '/m/09sy4'
. s:tequila s:source 'freebase'
. s:tequila s:inGroup s:getränk
. s:getränk rdfs:label 'Getränk'@en
. s:getränk s:source 'freebase'
. s:getränk s:id '/food/beverage'
. s:flasche s:hasGroup s:getränk
. s:flasche s:synonym s:coca-cola
. s:coca-cola rdfs:label 'Coca-Cola'@de
. s:coca-cola s:id '/en/coca-cola'
. s:coca-cola s:score '16.685852'
. s:coca-cola s:mid '/m/01yvs'
. s:coca-cola s:source 'freebase'
. s:coca-cola s:inGroup s:produktlinie
. s:flasche s:synonym s:molotowcocktail
. s:molotowcocktail rdfs:label 'Molotowcocktail'@de
. s:molotowcocktail s:id '/en/molotov_cocktail'
. s:molotowcocktail s:score '16.596401'
. s:molotowcocktail s:mid '/m/0585f'
. s:molotowcocktail s:source 'freebase'
. s:flasche s:synonym s:nansenflasche
. s:nansenflasche rdfs:label 'Nansenflasche'@de
. s:nansenflasche s:id '/en/nansen_bottle'
. s:nansenflasche s:score '16.521465'
. s:nansenflasche s:mid '/m/07cqlj'
. s:nansenflasche s:source 'freebase'
. s:flasche s:synonym s:bordeaux
. s:bordeaux rdfs:label 'Bordeaux'@de
. s:bordeaux s:id '/en/bordeaux_wine'
. s:bordeaux s:score '16.064312'
. s:bordeaux s:mid '/m/06rsz6'
. s:bordeaux s:source 'freebase'
. s:bordeaux s:inGroup s:literarisches_thema
. s:literarisches_thema rdfs:label 'Literarisches Thema'@en
. s:literarisches_thema s:source 'freebase'
. s:literarisches_thema s:id '/book/book_subject'
. s:flasche s:hasGroup s:literarisches_thema
. s:flasche s:synonym s:urinflasche
. s:urinflasche rdfs:label 'Urinflasche'@de
. s:urinflasche s:score '15.882382'
. s:urinflasche s:mid '/m/04ljn51'
. s:urinflasche s:source 'freebase'
. s:flasche s:hasGroup s:group_10615
. s:group_10615 rdfs:label 'group_10615'@de
. s:group_10615 s:source 'openthesaurus'
. s:group_10615 s:id '10615'
. s:flasche s:synonym s:buddel
. s:buddel rdfs:label 'Buddel'@de
. s:buddel s:level 'umgangssprachlich'
. s:buddel s:source 'openthesaurus'
. s:buddel s:inGroup s:group_10615
. s:flasche s:synonym s:kanne
. s:kanne rdfs:label 'Kanne'@de
. s:kanne s:level 'umgangssprachlich'
. s:kanne s:source 'openthesaurus'
. s:kanne s:inGroup s:group_10615
. s:flasche s:synonym s:phiole
. s:phiole rdfs:label 'Phiole'@de
. s:phiole s:level 'gehoben'
. s:phiole s:source 'openthesaurus'
. s:phiole s:inGroup s:group_10615
. s:flasche s:synonym s:pulle
. s:pulle rdfs:label 'Pulle'@de
. s:pulle s:level 'umgangssprachlich'
. s:pulle s:source 'openthesaurus'
. s:pulle s:inGroup s:group_10615
. s:flasche s:hasGroup s:group_10245
. s:group_10245 rdfs:label 'group_10245'@de
. s:group_10245 s:source 'openthesaurus'
. s:group_10245 s:id '10245'
. s:flasche s:synonym s:blindgänger
. s:blindgänger rdfs:label 'Blindgänger'@de
. s:blindgänger s:level 'umgangssprachlich'
. s:blindgänger s:source 'openthesaurus'
. s:blindgänger s:inGroup s:group_10245
. s:flasche s:synonym s:flabes_rheinland
. s:flabes_rheinland rdfs:label 'Flabes (Rheinland)'@de
. s:flabes_rheinland s:level 'umgangssprachlich'
. s:flabes_rheinland s:source 'openthesaurus'
. s:flabes_rheinland s:inGroup s:group_10245
. s:flasche s:synonym s:graupe
. s:graupe rdfs:label 'Graupe'@de
. s:graupe s:level 'umgangssprachlich'
. s:graupe s:source 'openthesaurus'
. s:graupe s:inGroup s:group_10245
. s:flasche s:synonym s:heini_ruhrdeutsch
. s:heini_ruhrdeutsch rdfs:label 'Heini (Ruhrdeutsch)'@de
. s:heini_ruhrdeutsch s:level 'umgangssprachlich'
. s:heini_ruhrdeutsch s:source 'openthesaurus'
. s:heini_ruhrdeutsch s:inGroup s:group_10245
. s:flasche s:synonym s:heiopei_rheinland
. s:heiopei_rheinland rdfs:label 'Heiopei (Rheinland)'@de
. s:heiopei_rheinland s:level 'umgangssprachlich'
. s:heiopei_rheinland s:source 'openthesaurus'
. s:heiopei_rheinland s:inGroup s:group_10245
. s:flasche s:synonym s:knalltüte
. s:knalltüte rdfs:label 'Knalltüte'@de
. s:knalltüte s:level 'umgangssprachlich'
. s:knalltüte s:source 'openthesaurus'
. s:knalltüte s:inGroup s:group_10245
. s:flasche s:synonym s:krücke
. s:krücke rdfs:label 'Krücke'@de
. s:krücke s:level 'umgangssprachlich'
. s:krücke s:source 'openthesaurus'
. s:krücke s:inGroup s:group_10245
. s:flasche s:synonym s:loser
. s:loser rdfs:label 'Loser'@de
. s:loser s:level 'umgangssprachlich'
. s:loser s:source 'openthesaurus'
. s:loser s:inGroup s:group_10245
. s:flasche s:synonym s:lulli
. s:lulli rdfs:label 'Lulli'@de
. s:lulli s:level 'umgangssprachlich'
. s:lulli s:source 'openthesaurus'
. s:lulli s:inGroup s:group_10245
. s:flasche s:synonym s:lusche
. s:lusche rdfs:label 'Lusche'@de
. s:lusche s:level 'umgangssprachlich'
. s:lusche s:source 'openthesaurus'
. s:lusche s:inGroup s:group_10245
. s:flasche s:synonym s:nichtskönner
. s:nichtskönner rdfs:label 'Nichtskönner'@de
. s:nichtskönner s:source 'openthesaurus'
. s:nichtskönner s:inGroup s:group_10245
. s:flasche s:synonym s:nichtsnutz_veraltet
. s:nichtsnutz_veraltet rdfs:label 'Nichtsnutz (veraltet)'@de
. s:nichtsnutz_veraltet s:source 'openthesaurus'
. s:nichtsnutz_veraltet s:inGroup s:group_10245
. s:flasche s:synonym s:niemand
. s:niemand rdfs:label 'Niemand'@de
. s:niemand s:source 'openthesaurus'
. s:niemand s:inGroup s:group_10245
. s:flasche s:synonym s:niete
. s:niete rdfs:label 'Niete'@de
. s:niete s:level 'umgangssprachlich'
. s:niete s:source 'openthesaurus'
. s:niete s:inGroup s:group_10245
. s:flasche s:synonym s:null
. s:null rdfs:label 'Null'@de
. s:null s:level 'umgangssprachlich'
. s:null s:source 'openthesaurus'
. s:null s:inGroup s:group_10245
. s:flasche s:synonym s:nulpe
. s:nulpe rdfs:label 'Nulpe'@de
. s:nulpe s:level 'umgangssprachlich'
. s:nulpe s:source 'openthesaurus'
. s:nulpe s:inGroup s:group_10245
. s:flasche s:synonym s:opfer_jugendsprachlich_2009
. s:opfer_jugendsprachlich_2009 rdfs:label 'Opfer (jugendsprachlich 2009)'@de
. s:opfer_jugendsprachlich_2009 s:level 'umgangssprachlich'
. s:opfer_jugendsprachlich_2009 s:source 'openthesaurus'
. s:opfer_jugendsprachlich_2009 s:inGroup s:group_10245
. s:flasche s:synonym s:pfeife
. s:pfeife rdfs:label 'Pfeife'@de
. s:pfeife s:level 'umgangssprachlich'
. s:pfeife s:source 'openthesaurus'
. s:pfeife s:inGroup s:group_10245
. s:flasche s:synonym s:pfeifenheini_regional
. s:pfeifenheini_regional rdfs:label 'Pfeifenheini (regional)'@de
. s:pfeifenheini_regional s:level 'umgangssprachlich'
. s:pfeifenheini_regional s:source 'openthesaurus'
. s:pfeifenheini_regional s:inGroup s:group_10245
. s:flasche s:synonym s:schmächtling
. s:schmächtling rdfs:label 'Schmächtling'@de
. s:schmächtling s:source 'openthesaurus'
. s:schmächtling s:inGroup s:group_10245
. s:flasche s:synonym s:taugenichts_veraltet
. s:taugenichts_veraltet rdfs:label 'Taugenichts (veraltet)'@de
. s:taugenichts_veraltet s:source 'openthesaurus'
. s:taugenichts_veraltet s:inGroup s:group_10245
. s:flasche s:synonym s:verlierer
. s:verlierer rdfs:label 'Verlierer'@de
. s:verlierer s:source 'openthesaurus'
. s:verlierer s:inGroup s:group_10245
. s:flasche s:synonym s:versager
. s:versager rdfs:label 'Versager'@de
. s:versager s:source 'openthesaurus'
. s:versager s:inGroup s:group_10245}}