insert data 
{ graph <http:cloudya.net/spinner/words> {
s:pickel rdfs:label 'pickel'@de
. s:pickel s:hasGroup s:group_3044
. s:group_3044 rdfs:label 'group_3044'@de
. s:group_3044 s:source 'openthesaurus'
. s:group_3044 s:id '3044'
. s:pickel s:synonym s:blase
. s:blase rdfs:label 'Blase'@de
. s:blase s:source 'openthesaurus'
. s:blase s:inGroup s:group_3044
. s:pickel s:synonym s:brandblase
. s:brandblase rdfs:label 'Brandblase'@de
. s:brandblase s:source 'openthesaurus'
. s:brandblase s:inGroup s:group_3044
. s:pickel s:synonym s:eiterbläschen
. s:eiterbläschen rdfs:label 'Eiterbläschen'@de
. s:eiterbläschen s:source 'openthesaurus'
. s:eiterbläschen s:inGroup s:group_3044
. s:pickel s:synonym s:hautblase
. s:hautblase rdfs:label 'Hautblase'@de
. s:hautblase s:source 'openthesaurus'
. s:hautblase s:inGroup s:group_3044
. s:pickel s:synonym s:luftblase
. s:luftblase rdfs:label 'Luftblase'@de
. s:luftblase s:source 'openthesaurus'
. s:luftblase s:inGroup s:group_3044
. s:pickel s:synonym s:pustel
. s:pustel rdfs:label 'Pustel'@de
. s:pustel s:source 'openthesaurus'
. s:pustel s:inGroup s:group_3044
. s:pickel s:synonym s:pustula
. s:pustula rdfs:label 'Pustula'@de
. s:pustula s:level 'fachsprachlich'
. s:pustula s:source 'openthesaurus'
. s:pustula s:inGroup s:group_3044
. s:pickel s:synonym s:wimmerl_bayr_österr
. s:wimmerl_bayr_österr rdfs:label 'Wimmerl (bayr., österr.)'@de
. s:wimmerl_bayr_österr s:level 'umgangssprachlich'
. s:wimmerl_bayr_österr s:source 'openthesaurus'
. s:wimmerl_bayr_österr s:inGroup s:group_3044
. s:pickel s:hasGroup s:group_10145
. s:group_10145 rdfs:label 'group_10145'@de
. s:group_10145 s:source 'openthesaurus'
. s:group_10145 s:id '10145'
. s:pickel s:synonym s:eispickel
. s:eispickel rdfs:label 'Eispickel'@de
. s:eispickel s:source 'openthesaurus'
. s:eispickel s:inGroup s:group_10145
. s:eispickel s:inGroup s:_business_product_category
. s:_business_product_category rdfs:label '/business/product_category'@en
. s:_business_product_category s:source 'freebase'
. s:_business_product_category s:id '/business/product_category'
. s:pickel s:synonym s:pickelhaube
. s:pickelhaube rdfs:label 'Pickelhaube'@de
. s:pickelhaube s:id '/en/pickelhaube'
. s:pickelhaube s:score '31.24622'
. s:pickelhaube s:mid '/m/061nz'
. s:pickelhaube s:source 'freebase'
. s:pickelhaube s:inGroup s:sammelkategorie
. s:sammelkategorie rdfs:label 'Sammelkategorie'@en
. s:sammelkategorie s:source 'freebase'
. s:sammelkategorie s:id '/interests/collection_category'
. s:pickel s:hasGroup s:sammelkategorie
. s:pickel s:synonym s:akne
. s:akne rdfs:label 'Akne'@de
. s:akne s:id '/en/acne_vulgaris'
. s:akne s:score '20.798698'
. s:akne s:mid '/m/0jwqt'
. s:akne s:source 'freebase'
. s:akne s:inGroup s:krankheit_oder_beschwerde
. s:krankheit_oder_beschwerde rdfs:label 'Krankheit oder Beschwerde'@en
. s:krankheit_oder_beschwerde s:source 'freebase'
. s:krankheit_oder_beschwerde s:id '/medicine/disease'
. s:pickel s:hasGroup s:krankheit_oder_beschwerde
. s:pickel s:synonym s:hacke
. s:hacke rdfs:label 'Hacke'@de
. s:hacke s:id '/en/hoe'
. s:hacke s:score '16.201103'
. s:hacke s:mid '/m/027sy7'
. s:hacke s:source 'freebase'
. s:hacke s:inGroup s:_business_product_category
. s:pickel s:hasGroup s:_business_product_category
. s:pickel s:synonym s:pickelville
. s:pickelville rdfs:label 'Pickelville'@de
. s:pickelville s:id '/en/pickelville'
. s:pickelville s:score '7.577643'
. s:pickelville s:mid '/m/04bzjv3'
. s:pickelville s:source 'freebase'
. s:pickelville s:inGroup s:großstadt_stadt_ortschaft
. s:großstadt_stadt_ortschaft rdfs:label 'Großstadt/Stadt/Ortschaft'@en
. s:großstadt_stadt_ortschaft s:source 'freebase'
. s:großstadt_stadt_ortschaft s:id '/location/citytown'
. s:pickel s:hasGroup s:großstadt_stadt_ortschaft}}